<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3id9drz\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3id9drz/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3id9drz.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3id9drz\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3id9drz\appProdProjectContainer([
    'container.build_hash' => '3id9drz',
    'container.build_id' => 'd85fb9c7',
    'container.build_time' => 1649146549,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3id9drz');
